<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Bank.Api\**\*.cs"
             Exclude="..\Bank.Api\bin\**;..\Bank.Api\obj\**"
             LinkBase="Api" />
    <None Include="..\Bank.Api\appsettings*.json"
          LinkBase="."
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.23" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bank.Application\Bank.Application.csproj" />
    <ProjectReference Include="..\Bank.Infrastructure\Bank.Infrastructure.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Bank.BuildingBlocks.Application\Bank.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Bank.Contracts\Bank.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Payments\Bank.Payments.Infrastructure\Bank.Payments.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Bank.Notifications.Infrastructure\Bank.Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Bank.Notifications.Presentation\Bank.Notifications.Presentation.csproj" />
    <ProjectReference Include="..\Modules\CoreBanking\Bank.CoreBanking.Presentation\Bank.CoreBanking.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Identity\Bank.Identity.Presentation\Bank.Identity.Presentation.csproj" />
  </ItemGroup>
</Project>
