<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Bank.Deposits.Domain\Bank.Deposits.Domain.csproj" />
    <ProjectReference Include="..\Bank.Deposits.Application\Bank.Deposits.Application.csproj" />
    <ProjectReference Include="..\Bank.Deposits.Infrastructure\Bank.Deposits.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Bank.BuildingBlocks.Application\Bank.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>
</Project>
