<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Bank.Statements.Application/Bank.Statements.Application.csproj" />
    <ProjectReference Include="../Bank.Statements.Infrastructure/Bank.Statements.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR" Version="12.4.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bank.Statements.Tests" />
  </ItemGroup>

</Project>
