<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Bank.Cards.Domain/Bank.Cards.Domain.csproj" />
        <ProjectReference Include="../../../BuildingBlocks/Bank.BuildingBlocks.Application/Bank.BuildingBlocks.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.2.0" />
    </ItemGroup>

</Project>
